# Generated by Django 4.0.2 on 2022-03-01 21:15

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('news', django_quill.fields.QuillField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='crossing',
            name='car_queue_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crossing',
            name='car_queue_wait_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crossing',
            name='pedestrian_queue_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crossing',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
