# Generated by Django 4.0.2 on 2022-03-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_news_crossing_car_queue_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='heading',
            field=models.CharField(default='Heading', max_length=200),
            preserve_default=False,
        ),
    ]
